/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n int1 -lang verilog -synth lse -bus_exp 7 -bb -arch xo3c00f -type iol -mode in -io_type LVTTL33 -width 1 -freq_in 100 -clk sclk -aligned -del -1 -gear 0  */
/* Fri Aug 14 13:50:48 2020 */


`timescale 1 ns / 1 ps
module int1 (clk, reset, sclk, datain, q)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk;
    input wire reset;
    input wire [0:0] datain;
    output wire sclk;
    output wire [0:0] q;

    wire scuba_vhi;
    wire dataini_t0;
    wire buf_clk;
    wire buf_dataini0;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    IFS1P3DX Inst3_IFS1P3DX0 (.D(dataini_t0), .SP(scuba_vhi), .SCLK(buf_clk), 
        .CD(reset), .Q(q[0]));

    IB Inst2_IB (.I(clk), .O(buf_clk))
             /* synthesis IO_TYPE="LVTTL33" */;

    IB Inst1_IB0 (.I(datain[0]), .O(buf_dataini0))
             /* synthesis IO_TYPE="LVTTL33" */;

    assign sclk = buf_clk;
    assign dataini_t0 = buf_dataini0;


    // exemplar begin
    // exemplar attribute Inst2_IB IO_TYPE LVTTL33
    // exemplar attribute Inst1_IB0 IO_TYPE LVTTL33
    // exemplar end

endmodule
