

// TOOL:     vlog2tf
// DATE:     Fri Aug 14 12:43:08 2020
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   load_register
// DESIGN:   load_register
// FILENAME: load_register_tf.v
// PROJECT:  Trial_Schematic
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module load_register_tf();

// Inputs
    reg [13:0] D;
    reg Clk;
    reg reset;
    reg load;


// Outputs
    wire [13:0] out_data;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    load_register UUT (
        .D(D), 
        .Clk(Clk), 
        .reset(reset), 
        .load(load), 
        .out_data(out_data)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            D = 0;
            Clk = 0;
            reset = 0;
            load = 0;
    end

endmodule // load_register_tf