/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Fri Aug 14 14:07:43 2020 */

/* parameterized module instance */
PLL __ (.CLKI( ), .RST( ), .CLKOP( ));
