/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* Fri Aug 14 13:53:40 2020 */

/* parameterized module instance */
Stable_Data __ (.clk( ), .clkout( ), .reset( ), .sclk( ), .d( ), 
    .dout( ));
